### ISSUE TITLE
Harley 1-2-9 Foci Detection Foci Table xlsx file export failure

### ISSUE THREAD

**Issue by nickpmort** [lnilya/harley#12]
When trying to save Foci Detection Foci Table output files in Harley 1-2-9, I am getting the attached error messages. These errors occur regardless of file path, file name, or .xlsx file extension. Thank you for your input!
![Harley-1-2-9_Foci_xlsx_Error_screen](https://github.com/lnilya/harley/assets/144734878/28588ce2-b93e-4265-a8ec-c4ceebc8e999)
![Harley-1-2-9_Foci_xlsx_Error](https://github.com/lnilya/harley/assets/144734878/b9a5a136-433e-4f74-a102-d4efa40241d9)

**Comment by lnilya** [comment]
Should be fixed in Version 1.2.11 on mac and windows.
